# Generated by Django 3.0.7 on 2020-06-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='magic_key',
            field=models.CharField(default='kncFca', editable=False, max_length=6),
        ),
    ]
