# Generated by Django 3.0.7 on 2020-06-28 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200623_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_choice', models.CharField(choices=[('roast', 'ROAST'), ('boast', 'BOAST')], max_length=50)),
                ('text', models.CharField(max_length=280)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('submission_time', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)),
                ('magic_key', models.CharField(default='CkbTlZ', editable=False, max_length=6)),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='PostItem',
        ),
    ]
